
"""add_embedding_column_and_extensions

Revision ID: 21b492ac9cdf
Revises: 8f0a13172fd7
Create Date: 2026-01-29 03:20:03.557786

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '21b492ac9cdf'
down_revision = '8f0a13172fd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sanction', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sanction', 'embedding')
    # ### end Alembic commands ###
