
"""create_tables

Revision ID: 61c49526b19a
Revises: 000000000001
Create Date: 2025-12-13 20:47:09.936466

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '61c49526b19a'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_documents_id'), 'entity_documents', ['id'], unique=False)
    op.create_index(op.f('ix_entity_documents_name'), 'entity_documents', ['name'], unique=False)
    op.create_table('sanction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanction_entity_name'), 'sanction', ['entity_name'], unique=False)
    op.create_index(op.f('ix_sanction_id'), 'sanction', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sanction_id'), table_name='sanction')
    op.drop_index(op.f('ix_sanction_entity_name'), table_name='sanction')
    op.drop_table('sanction')
    op.drop_index(op.f('ix_entity_documents_name'), table_name='entity_documents')
    op.drop_index(op.f('ix_entity_documents_id'), table_name='entity_documents')
    op.drop_table('entity_documents')
    # ### end Alembic commands ###
