
"""Add XML fields to Sanction model

Revision ID: 8f0a13172fd7
Revises: 9be348269438
Create Date: 2026-01-19 21:42:28.446990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0a13172fd7'
down_revision = '9be348269438'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sanction', sa.Column('data_id', sa.String(), nullable=True))
    op.add_column('sanction', sa.Column('un_list_type', sa.String(), nullable=True))
    op.add_column('sanction', sa.Column('reference_number', sa.String(), nullable=True))
    op.add_column('sanction', sa.Column('listed_on', sa.Date(), nullable=True))
    op.add_column('sanction', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('sanction', sa.Column('designation', sa.JSON(), nullable=True))
    op.add_column('sanction', sa.Column('aliases', sa.JSON(), nullable=True))
    op.add_column('sanction', sa.Column('addresses', sa.JSON(), nullable=True))
    op.add_column('sanction', sa.Column('birth_dates', sa.JSON(), nullable=True))
    op.add_column('sanction', sa.Column('birth_places', sa.JSON(), nullable=True))
    op.add_column('sanction', sa.Column('documents', sa.JSON(), nullable=True))
    op.add_column('sanction', sa.Column('last_updated', sa.Date(), nullable=True))
    op.alter_column('sanction', 'remarks',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_sanction_data_id'), 'sanction', ['data_id'], unique=True)
    op.create_index(op.f('ix_sanction_reference_number'), 'sanction', ['reference_number'], unique=False)
    op.create_index(op.f('ix_sanction_un_list_type'), 'sanction', ['un_list_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanction_un_list_type'), table_name='sanction')
    op.drop_index(op.f('ix_sanction_reference_number'), table_name='sanction')
    op.drop_index(op.f('ix_sanction_data_id'), table_name='sanction')
    op.alter_column('sanction', 'remarks',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('sanction', 'last_updated')
    op.drop_column('sanction', 'documents')
    op.drop_column('sanction', 'birth_places')
    op.drop_column('sanction', 'birth_dates')
    op.drop_column('sanction', 'addresses')
    op.drop_column('sanction', 'aliases')
    op.drop_column('sanction', 'designation')
    op.drop_column('sanction', 'gender')
    op.drop_column('sanction', 'listed_on')
    op.drop_column('sanction', 'reference_number')
    op.drop_column('sanction', 'un_list_type')
    op.drop_column('sanction', 'data_id')
    # ### end Alembic commands ###
