
"""add_audit_fields_to_user

Revision ID: 9be348269438
Revises: 61c49526b19a
Create Date: 2025-12-13 21:25:19.591831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be348269438'
down_revision = '61c49526b19a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'created_by_id')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
